[package]
name = "challenge10"
version = "0.1.0"
authors = ["rsmitsuda <rsmitsuda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.30"
base64 = "0.12.3"
