[package]
name = "webscraper"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
reqwest = "0.10.4"
select = "0.4.3"
scraper = "0.12.0"
tokio = {version = "0.2.21", features = ["full"]}
